name: Test, Build and Deploy
run-name: Deploy live site
on: [push, workflow_dispatch]
jobs:
  Build-Files:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - run: echo "✅ Repo ${{ github.repository }} cloned to ${{ github.workspace }}"
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: echo "✅ Node modules installed"
      - run: npm run test:live
      - run: echo "✅ Tests successfully run"
      - run: npm run build:live
      - run: echo "✅ Live files created"
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: echo "✅ doctl installed"
      - run: cd dist
      - name: Deploy to DigitalOcean App Platform
        run: doctl apps create-deployment ${{ secrets.DIGITALOCEAN_APP_ID }} -v
        env:
          APP_ID: ${{ secrets.DIGITALOCEAN_APP_ID }}
      - run: echo "✅ App deployed"
