name: Test, Build and Deploy
run-name: Deploy live site
on: [push, workflow_dispatch]
jobs:
  Build-Files:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - run: echo "✅ Repo ${{ github.repository }} cloned to ${{ github.workspace }}"
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: echo "✅ Node modules installed"
      - run: npm run test:live
      - run: echo "✅ Tests successfully run"
      - run: npm run build:live
      - run: echo "✅ Live files created"
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          workingDirectory: dist
          directory: .
      - run: echo "✅ Published to Cloudflare Pages"
